//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using Windows.ApplicationModel.Resources;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static ResourceLoader resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static ResourceLoader ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceLoader temp = ResourceLoader.GetForCurrentView("Appirater/Resources");
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key);
        }

        /// <summary>
        ///   Looks up a localized string similar to Rate {0}
        /// </summary>
        public static string rate_title
        {
            get
            {
                return ResourceManager.GetString("rate_title");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you enjoy using {0}, would you mind taking a moment to rate it? Thanks for your support!
        /// </summary>
        public static string rate_message
        {
            get
            {
                return ResourceManager.GetString("rate_message");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, Rate {0}
        /// </summary>
        public static string rate
        {
            get
            {
                return ResourceManager.GetString("rate");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remind me later
        /// </summary>
        public static string rate_later
        {
            get
            {
                return ResourceManager.GetString("rate_later");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No, Thanks
        /// </summary>
        public static string rate_cancel
        {
            get
            {
                return ResourceManager.GetString("rate_cancel");
            }
        }

    }

